### PR TITLE
Adjusted Button Spacing and Borders

### PR DESCRIPTION
**Pull request by chaitjo**

### CODE REVIEW

**Comment by SuyashLakhotia** [comment]
Why have you added and deleted the same lines?

**Comment by chaitjo** [comment]
I don't know why the diff is like that, but here are the changes:
- Normal button width
- Social button hover, border and spacing (between them)

**Comment by chaitjo** [comment]
I think it has something to do with me dragging-and-dropping to upload files, thus overwriting them.

**Comment by SuyashLakhotia** [comment]
Lol. Do you mind properly committing and sending a PR?

**Pull request closed without merging**
